<?xml version="1.0"?>
<!DOCTYPE recordings_file [   <!ELEMENT recordings_file (comments, file_path, recording+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT file_path (#PCDATA)>
   <!ELEMENT recording (filename, role, model_genres, title, artist)>
   <!ELEMENT filename (#PCDATA)>
   <!ELEMENT role (#PCDATA)>
   <!ELEMENT model_genres (genre*)>
   <!ELEMENT genre (#PCDATA)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT artist (#PCDATA)>
]>

<recordings_file>

   <comments></comments>

   <file_path>C:\Bodhidharma\MIDI_Files</file_path>

   <recording>
      <filename>against.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Against All Odds</title>
      <artist>Phil Collins</artist>
   </recording>

   <recording>
      <filename>anyplace.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Anytime, Anyplace</title>
      <artist>Janet Jackson</artist>
   </recording>

   <recording>
      <filename>anytime.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Anytime you Need a Friend</title>
      <artist>Mariah Carey</artist>
   </recording>

   <recording>
      <filename>carly_simon_nobody_does_it_better.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Nobody Does it Better</title>
      <artist>Carly Simon</artist>
   </recording>

   <recording>
      <filename>celine_dion_all_by_myself.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>All by Myself</title>
      <artist>Celine Dion</artist>
   </recording>

   <recording>
      <filename>comeback.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Come Back to Me</title>
      <artist>Janet Jackson</artist>
   </recording>

   <recording>
      <filename>go_the_distance.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Go the Distance</title>
      <artist>Michael Bolton</artist>
   </recording>

   <recording>
      <filename>haveitoldyoulately.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Have I Told You Lately</title>
      <artist>Rod Stewart</artist>
   </recording>

   <recording>
      <filename>HELLO.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Hello</title>
      <artist>Lionel Ritchie</artist>
   </recording>

   <recording>
      <filename>holding.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Holding back the Tears</title>
      <artist>Simply Red</artist>
   </recording>

   <recording>
      <filename>how_am_i_supposwithout_you.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>How am I Supposed to Live Without You</title>
      <artist>Michael Bolton</artist>
   </recording>

   <recording>
      <filename>i'll_never_break_your_heart.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>I'll Never Break Your Heart</title>
      <artist>Backstreet Boys</artist>
   </recording>

   <recording>
      <filename>in2deep.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>In Too Deep</title>
      <artist>Phil Collins</artist>
   </recording>

   <recording>
      <filename>it's_all_comingk_to_me_now.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>It's All Coming to Me Now</title>
      <artist>Celine Dion</artist>
   </recording>

   <recording>
      <filename>looking.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Looking In</title>
      <artist>Mariah Carey</artist>
   </recording>

   <recording>
      <filename>Private_Emotion.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Private Emotion</title>
      <artist>Enrique Iglesias</artist>
   </recording>

   <recording>
      <filename>suddenly.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Suddenly</title>
      <artist>Billy Ocean</artist>
   </recording>

   <recording>
      <filename>think_twice.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Think Twice</title>
      <artist>Celine Dion</artist>
   </recording>

   <recording>
      <filename>three_times_a_lady.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Three Times a Lady</title>
      <artist>Lionel Ritchie</artist>
   </recording>

   <recording>
      <filename>truecols.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>True Colors</title>
      <artist>Cyndi Lauper</artist>
   </recording>

   <recording>
      <filename>unbreak.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Unbreak my Heart</title>
      <artist>Toni Braxton</artist>
   </recording>

   <recording>
      <filename>vision.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Vision of Love</title>
      <artist>Mariah Carey</artist>
   </recording>

   <recording>
      <filename>whitney_didntwealmosthaveitall.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Didn't We Almost Have it All</title>
      <artist>Whitney Houston</artist>
   </recording>

   <recording>
      <filename>Whitney_houston_i_will_always_love_you.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>I Will Always Love You</title>
      <artist>Whitney Houston</artist>
   </recording>

   <recording>
      <filename>yursong.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Adult Contemporary</genre>
      </model_genres>
      <title>Your Song</title>
      <artist>Elton John</artist>
   </recording>

   <recording>
      <filename>Aenima.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Aenima</title>
      <artist>Tool</artist>
   </recording>

   <recording>
      <filename>alive.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Alive</title>
      <artist>Pearl Jam</artist>
   </recording>

   <recording>
      <filename>ASK4IT2.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Ask For It</title>
      <artist>Hole</artist>
   </recording>

   <recording>
      <filename>BLKHOLE.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Black Hole Sun</title>
      <artist>Soundgarden</artist>
   </recording>

   <recording>
      <filename>bluemon.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Blue Monday</title>
      <artist>Orgy</artist>
   </recording>

   <recording>
      <filename>Bound_For_The_Floor.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Bound for the Floor</title>
      <artist>Local H</artist>
   </recording>

   <recording>
      <filename>december.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>December</title>
      <artist>Collective Soul</artist>
   </recording>

   <recording>
      <filename>Flagpole_Sitta.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Flagpole Sitta</title>
      <artist>Harvey Danger</artist>
   </recording>

   <recording>
      <filename>gel.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Gel</title>
      <artist>Collective Soul</artist>
   </recording>

   <recording>
      <filename>Heart_Shaped_Box.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Heart Shaped Box</title>
      <artist>Nirvana</artist>
   </recording>

   <recording>
      <filename>heaven.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Heaven Beside You</title>
      <artist>Alice in Chains</artist>
   </recording>

   <recording>
      <filename>Higher.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Higher</title>
      <artist>Creed</artist>
   </recording>

   <recording>
      <filename>jesus_freak.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Jesus Freak</title>
      <artist>DC Talk</artist>
   </recording>

   <recording>
      <filename>lithium.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Lithium</title>
      <artist>Nirvana</artist>
   </recording>

   <recording>
      <filename>MY_WAVE.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>My Wave</title>
      <artist>Soundgarden</artist>
   </recording>

   <recording>
      <filename>myfavgame.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>My Favorite Game</title>
      <artist>Cardigans</artist>
   </recording>

   <recording>
      <filename>plush.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Plush</title>
      <artist>Stone Temple Pilots</artist>
   </recording>

   <recording>
      <filename>PRECIOUS.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Precious Declaration</title>
      <artist>Collective Soul</artist>
   </recording>

   <recording>
      <filename>ROOSTER.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Rooster</title>
      <artist>Alice In Chains</artist>
   </recording>

   <recording>
      <filename>Smells_Like_Teen_Spirit.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Smells Like Teen Spirit</title>
      <artist>Nirvana</artist>
   </recording>

   <recording>
      <filename>SMONICA.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Santa Monica</title>
      <artist>Everclear</artist>
   </recording>

   <recording>
      <filename>The_Distance.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Distance</title>
      <artist>Cake</artist>
   </recording>

   <recording>
      <filename>where_the_river_flows.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Where the River Flows</title>
      <artist>Collective Soul</artist>
   </recording>

   <recording>
      <filename>WHEREBOY.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Where Boys Fear to Tread</title>
      <artist>The Smashing Pumpkins</artist>
   </recording>

   <recording>
      <filename>WOULD.MID</filename>
      <role>classification</role>
      <model_genres>
         <genre>Alternative Rock</genre>
      </model_genres>
      <title>Would</title>
      <artist>Alice In Chains</artist>
   </recording>

   <recording>
      <filename>ac_chantons.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Chantons, chantons, et nous rejouissons</title>
      <artist>Andre Campra</artist>
   </recording>

   <recording>
      <filename>av_molti2.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Concerto Do maggiore RV558 con molti stromenti</title>
      <artist>Vivaldi</artist>
   </recording>

   <recording>
      <filename>av002a1.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Four Seasons La Primavera Allegro</title>
      <artist>Vivaldi</artist>
   </recording>

   <recording>
      <filename>av003.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Concerto No.6 in A</title>
      <artist>Vivaldi</artist>
   </recording>

   <recording>
      <filename>b0028_6.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Zeuch ein zu deinen Toren</title>
      <artist>Bach</artist>
   </recording>

   <recording>
      <filename>b0424.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Was bist du doch, o Seele, so betru</title>
      <artist>Bach</artist>
   </recording>

   <recording>
      <filename>bach531.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Prelude And Fugue For Organ In C</title>
      <artist>J. S. Bach</artist>
   </recording>

   <recording>
      <filename>bach7.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Sinfonia No. 8</title>
      <artist>J. S. Bach </artist>
   </recording>

   <recording>
      <filename>bux_cfug.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Fugue In C</title>
      <artist>Buxtehude</artist>
   </recording>

   <recording>
      <filename>cibux183.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Durch Adams Fall</title>
      <artist> Buxtehude </artist>
   </recording>

   <recording>
      <filename>cm_altri_canti_damor.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Altri canti d'Amor</title>
      <artist>Claudio Monteverdi</artist>
   </recording>

   <recording>
      <filename>cm_combattimento1.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Ne Vol Tancredi et Notte, Che Nel Profondo</title>
      <artist>Monteverdi</artist>
   </recording>

   <recording>
      <filename>cm_ecco_pur.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Ecco pur, ch'a voi ritorno</title>
      <artist>Claudio Monteverdi</artist>
   </recording>

   <recording>
      <filename>cm_tu_se_morta.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>L'Orfeo, Tu se morta</title>
      <artist>Monteverdi</artist>
   </recording>

   <recording>
      <filename>gfh_se_bramate_damar.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Se bramate d'amar</title>
      <artist>Handel</artist>
   </recording>

   <recording>
      <filename>gfh_va_tacito.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Va tacito e nascosto</title>
      <artist>Handel</artist>
   </recording>

   <recording>
      <filename>hand3.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Concerti Grossi Op.6 No.4 in A- Allegro</title>
      <artist>Handel</artist>
   </recording>

   <recording>
      <filename>hand6.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Gavotte For Flute With Harpsichord And Cello</title>
      <artist>Handel</artist>
   </recording>

   <recording>
      <filename>hp_amin.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Minuet in A minor</title>
      <artist>Henry Purcell</artist>
   </recording>

   <recording>
      <filename>hp_when_i_am.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>When I am laid in earth</title>
      <artist>Henry Purcell</artist>
   </recording>

   <recording>
      <filename>k030.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Cat Fugue</title>
      <artist>Scarlatti</artist>
   </recording>

   <recording>
      <filename>k058.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Fugue, Esercizzio or Sonata, K 058</title>
      <artist>Scarlatti</artist>
   </recording>

   <recording>
      <filename>nun_komm_der_heiden_heiland.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Nun komm der Heiden Heiland</title>
      <artist>Pachelbel</artist>
   </recording>

   <recording>
      <filename>papillon.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Les Papillons</title>
      <artist>Couperin</artist>
   </recording>

   <recording>
      <filename>pfc_auree_trecce.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Baroque</genre>
      </model_genres>
      <title>Auree trecce inanellate</title>
      <artist>Pier Francesco Cavalli </artist>
   </recording>

   <recording>
      <filename>4on6.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>4 on 6</title>
      <artist>Wes Montgomery</artist>
   </recording>

   <recording>
      <filename>4thAvenueTheme.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>4th Avenue Theme</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>52ndst.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>52nd Street</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>airegin.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Airegin</title>
      <artist>Sonny Rollins</artist>
   </recording>

   <recording>
      <filename>auprvave.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Au Privave</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>billiesb.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Billie's Bounce</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>Bluenboo.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Blue 'N Boogie</title>
      <artist>Dizzy Gillespie</artist>
   </recording>

   <recording>
      <filename>cooker_benson.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Cooker</title>
      <artist>George Benson</artist>
   </recording>

   <recording>
      <filename>dexterity.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Donna Lee</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>donnalee.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Donna Lee</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>evidence.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Evidence</title>
      <artist>Thelonious Monk</artist>
   </recording>

   <recording>
      <filename>grooving.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Grooving High</title>
      <artist>Dizzy Gillespie</artist>
   </recording>

   <recording>
      <filename>halfn.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Half Nelson</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>havejones.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Have You Met Miss Jones?</title>
      <artist>Oscar Peterson</artist>
   </recording>

   <recording>
      <filename>inwalked.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>In Walked Bud</title>
      <artist>Thelonious Monk</artist>
   </recording>

   <recording>
      <filename>lazybird.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Lazy Bird</title>
      <artist>John Coletrane</artist>
   </recording>

   <recording>
      <filename>mrpc.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Mr. P. C.</title>
      <artist>John Coletrane</artist>
   </recording>

   <recording>
      <filename>offminor.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Bebop</title>
      <artist>Thelonious Monk</artist>
   </recording>

   <recording>
      <filename>ornith.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Ornithology</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>richjazz.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Rich Jazz</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>scrapple.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Scrapple From the Apple</title>
      <artist>Charlie Parker</artist>
   </recording>

   <recording>
      <filename>softly.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Softly as in a Morning Sunrise</title>
      <artist>Modern Jazz Quartet</artist>
   </recording>

   <recording>
      <filename>straightn.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Straight No Chaser</title>
      <artist>Thelonious Monk</artist>
   </recording>

   <recording>
      <filename>wellyou.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Well, You Needn't</title>
      <artist>Thelonious Monk</artist>
   </recording>

   <recording>
      <filename>whisper.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bebop</genre>
      </model_genres>
      <title>Whisper</title>
      <artist>Benny Golson</artist>
   </recording>

   <recording>
      <filename>allthegoodtimes.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>All the Good Times</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>angeline.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Angeline</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>arkansas.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Arkansas Traveller</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>ballad.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Ballad of Jesse James</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>banjointhehollow.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Banjo in the Hollow</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>banjosignal.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Banjo Signal</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>banksoftheohio.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Banks of the Ohio</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>blackberry1.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Blackberry Blossom</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>BlueGrass.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Blue Grass</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>bluegrassboogie.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Bluegrass Boogie</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>cherokee.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Cherokee</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>countryroads.mid</filename>
      <role>classification</role>
      <model_genres>
         <genre>Bluegrass</genre>
      </model_genres>
      <title>Country Roads</title>
      <artist>Anonymous</artist>
   </recording>

   <recording>
      <filename>downyonder.mid</filename>
      <role>classification</role>
      <model_genres>